{
 "title": "Nukumori",
 "description": "A Dashboard to monitor Synology NAS",
 "tags": [
  "Influxdb",
  "Synology"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "influxdb", "label": "InfluxDB", "query": "influxdb" },
   {
    "name": "host",
    "label": "Server:",
    "query": "SHOW TAG VALUES FROM \"snmp.SYNO\" WITH KEY = \"agent_host\""
   },
   {
    "name": "intf",
    "label": "Interface:",
    "query": "SHOW TAG VALUES FROM \"ifTable\" WITH KEY = \"ifDescr\" WHERE \"agent_host\" =~ /^$host/ AND \"ifDescr\" =~ /^(bond|eth)/"
   },
   {
    "name": "disk",
    "label": "Disk:",
    "query": "SHOW TAG VALUES FROM \"storageIOTable\" WITH KEY = \"storageIODevice\" WHERE \"agent_host\" =~ /^$host/"
   }
  ]
 },
 "panels": [
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nukumori",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "$col",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "measurement": "snmp.SYNO",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "modelName" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Model" ], "type": "alias" }
      ],
      [
       { "params": [ "serialNumber" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Serial Number" ], "type": "alias" }
      ],
      [
       { "params": [ "version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "DSM Version" ], "type": "alias" }
      ],
      [
       { "params": [ "sysDescr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Kernel" ], "type": "alias" }
      ],
      [
       { "params": [ "upgradeAvailable" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "DSM Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Nukumori" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "snmp.SYNO",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Nukumori" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "measurement": "system",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"uptime_format\") AS \"value\" FROM \"system\" WHERE \"host\" =~ /$server$/",
     "select": [
      [
       { "params": [ "n_cpus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Nukumori" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "measurement": "snmp.SYNO",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"uptime_format\") AS \"value\" FROM \"system\" WHERE \"host\" =~ /$server$/",
     "select": [
      [
       { "params": [ "memTotalReal" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Nukumori" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "measurement": "snmp.SYNO",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"uptime_format\") AS \"value\" FROM \"system\" WHERE \"host\" =~ /$server$/",
     "select": [
      [
       { "params": [ "memTotalSwap" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Nukumori" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "measurement": "system",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"uptime_format\") AS \"value\" FROM \"system\" WHERE \"host\" =~ /$server$/",
     "select": [
      [
       { "params": [ "uptime_format" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Nukumori" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Raid Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Volume 1",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "raidName" ], "type": "tag" }
     ],
     "measurement": "raidTable",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"raidStatus\") FROM \"raidTable\" WHERE (\"host\" = 'Nukumori' AND \"raidName\" = 'Volume 1') AND $timeFilter",
     "select": [
      [
       { "params": [ "raidStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Resource",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "CPU Usage",
     "measurement": "cpu",
     "query": "SELECT last(\"usage_idle\") * - 1 + 100 FROM \"cpu\" WHERE (\"host\" = 'Nukumori' AND \"cpu\" = 'cpu-total') AND $timeFilter",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Memory Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"used_percent\") FROM \"mem\" WHERE (\"host\" = 'Nukumori') AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Disk($tag_storageIODevice) Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"storageIOLA1\") FROM \"storageIOTable\" WHERE (\"host\" = 'Nukumori' AND \"storageIODevice\" =~ /^$disk$/) AND $timeFilter GROUP BY time($__interval), \"storageIODevice\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Volume & Capacity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "OS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"used_percent\" FROM \"disk\" WHERE (\"host\" = 'Nukumori' AND \"device\" = 'md0') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "SHR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"used_percent\" FROM \"disk\" WHERE (\"host\" = 'Nukumori' AND \"device\" = 'mapper/cachedev_0') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Overall Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "snmp.SYNO",
     "select": [
      [
       { "params": [ "systemStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Nukumori" }
     ]
    }
   ]
  },
  {
   "title": "Power Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "measurement": "snmp.SYNO",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "powerStatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Nukumori" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Fan Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "agent_host" ], "type": "tag" }
     ],
     "measurement": "snmp.SYNO",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "cpuFanStatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Nukumori" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "System Fan Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "measurement": "snmp.SYNO",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "systemFanStatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Nukumori" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "UPS Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "measurement": "hrStorageTable",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "SELECT last(\"uptime_format\") AS \"value\" FROM \"system\" WHERE \"host\" =~ /$server$/",
     "select": [
      [
       { "params": [ "upsDeviceModel" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Nukumori" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "UPS Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "measurement": "hrStorageTable",
     "select": [
      [
       { "params": [ "upsLoad" ], "type": "field" }
      ],
      [
       { "params": [ "upsCharge" ], "type": "field" }
      ],
      [
       { "params": [ "upsWarning" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Nukumori" }
     ]
    }
   ]
  },
  {
   "title": "UPS Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "measurement": "hrStorageTable",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "SELECT \"upsCharge\" FROM \"hrStorageTable\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "upsCharge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Nukumori" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk Model & Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "diskID" ], "type": "tag" }
     ],
     "measurement": "diskTable",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "diskModel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Model" ], "type": "alias" }
      ],
      [
       { "params": [ "diskType" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Type" ], "type": "alias" }
      ],
      [
       { "params": [ "diskStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Nukumori" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk Temperature",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "alias": "$tag_diskID",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "diskID" ], "type": "tag" }
     ],
     "measurement": "diskTable",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "diskTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Nukumori" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 100 - last(\"usage_idle\") FROM \"cpu\" WHERE (\"host\" = 'Nukumori' AND \"cpu\" =~ /cpu[0-99].*/) AND $timeFilter GROUP BY time($interval), \"cpu\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(used) as used, last(cached) as cached, last(free) as free, last(buffered) as buffered  FROM \"mem\" WHERE host = 'Nukumori' AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_storageIODevice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "storageIODevice" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "storageIOTable",
     "select": [
      [
       { "params": [ "storageIOLA1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Nukumori" },
      { "condition": "AND", "key": "storageIODevice", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_ifDescr:$col",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ifDescr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifTable",
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "ifInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "in" ], "type": "alias" }
      ],
      [
       { "params": [ "ifOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Nukumori" },
      { "condition": "AND", "key": "ifDescr", "operator": "=~", "value": "/^$intf$/" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_laNames",
     "bucketAggs": [
      { "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "groupBy": [
      { "params": [ "auto" ], "type": "time" },
      { "params": [ "laNames" ], "type": "tag" }
     ],
     "measurement": "laTable",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "select": [
      [
       { "params": [ "laLoadInt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Nukumori" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk I/O Total",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "none", "label": "op/s" }
   ],
   "targets": [
    {
     "alias": "$tag_storageIODevice:read/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "storageIODevice" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "storageIOTable",
     "select": [
      [
       { "params": [ "storageIOReads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Nukumori" },
      { "condition": "AND", "key": "storageIODevice", "operator": "=~", "value": "/^$disk$/" }
     ]
    },
    {
     "alias": "$tag_storageIODevice:write/s",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "storageIODevice" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "storageIOTable",
     "select": [
      [
       { "params": [ "storageIOWrites" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Nukumori" },
      { "condition": "AND", "key": "storageIODevice", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Volume & Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Volume 1 (Volume & Capacity)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "volume 1:total",
     "measurement": "raidTable",
     "query": "SELECT last(\"raidTotalSize\") FROM \"raidTable\" WHERE (\"host\" = 'Nukumori' AND \"raidName\" = 'Volume 1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "raidTotalSize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "raidName", "operator": "=", "value": "Volume 1" }
     ]
    },
    {
     "alias": "volume 1:free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "raidTable",
     "query": "SELECT mean(\"raidFreeSize\") FROM \"raidTable\" WHERE (\"host\" = 'Nukumori' AND \"raidName\" = 'Volume 1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "raidTotalSize" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "raidName", "operator": "=", "value": "Volume 1" }
     ]
    },
    {
     "alias": "volume 1:used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"raidTotalSize\") - last(\"raidFreeSize\") FROM \"raidTable\" WHERE (\"host\" = 'Nukumori' AND \"raidName\" = 'Volume 1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}