version: '3.8'
services:
  telegraf:
    image: telegraf:1.8
    container_name: telegraf
    hostname: telegraf
    restart: always
    network_mode: "host"
    volumes:
      - ./telegraf/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro 
      - /usr/share/snmp/mibs:/usr/share/snmp/mibs:ro
      - /:/hostfs:ro

  influxdb:
    image: influxdb:1.8 
    container_name: influxdb
    hostname: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ./influxdb/library:/var/lib/influxdb
    command: -config /etc/influxdb/influxdb.conf

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/config:/etc/grafana
      - ./grafana/library:/var/lib/grafana
